### PR TITLE
adds peer locations

### PR DESCRIPTION
**Pull request by cfhull**
image

Closes https://github.com/Hyperobjekt/spi-map/issues/34 https://github.com/Hyperobjekt/spi-map/issues/33

### CODE REVIEW

**Comment by james-minton** [comment]
@cfhull, great to see this working. The text styles are nice but seem to suggest buttons, like I could click on these and produce some result, such as adding the location to the scorecard. Great if that's actually easy to do, otherwise I think a simple comma-separated list would be best here.

**Comment by cfhull** [comment]
I'm not seeing an easy way to programatically select a location. I'm also not sure how to comma separate the cities in a way that looks good, unless you want to remove the state when listing cities?

image

**Comment by james-minton** [comment]
@cfhull gotcha, how about a "•" as a separator? (Like a list item dot)

**Comment by cfhull** [comment]
I pushed those updates. Let me know what you think

**Comment by james-minton** [comment]
Cool! @cfhull one last thing, could we un-bold the bolding? Like so:

Screen Shot 2022-11-29 at 4 36 07 PM

**Comment by cfhull** [comment]
@james-minton Done!

**Pull request merged**
