### PR TITLE
Remove column

### PR DESCRIPTION
**Pull request by cfhull**
image

### CODE REVIEW

**Comment by james-minton** [comment]
@cfhull thanks for the quick work on this! A bit of design finesse --

Move the X slightly down:

```
.scorecard__location-remove {
    position: absolute;
    top: 4px; /* change to this */
    right: 2px;
    height: 24px;
    width: 24px;
}
```
Reduce height of colored bar:

```
.scorecard__location-color {
    width: 6px;
    border-radius: 4px;
    position: absolute;
    right: 11px;
    top: 32px; /* change to this */
    bottom: 20px;
}
```

Then in terms of functionality: the best UX would probably be to close the scorecard entirely once the last column has been removed. Is this easily doable?

**Comment by cfhull** [comment]
> Move the X slightly down

> Reduce height of colored bar

> Then in terms of functionality: the best UX would probably be to close the scorecard entirely once the last column has been removed. Is this easily doable?

@james-minton  Makes sense, and looks good. I pushed those updates.

**Comment by james-minton** [comment]
@cfhull not necessary tonight! But I'm good with merging this when able -- just needs some merge conflicts resolved.

**Comment by cfhull** [comment]
> @cfhull not necessary tonight! But I'm good with merging this when able -- just needs some merge conflicts resolved.

Done!

**Pull request merged**
